import {
  Plus,
  User,
  KeyRound,
  Eye,
  EyeOff,
  ArrowRight,
  ArrowDown,
  Check,
  Pencil,
  List,
  Menu,
  X,
  Trash2,
  Calendar,
  Boxes,
  ArrowLeft,
  ArrowUp,
  Search
} from 'lucide-react'

export const icons = {
  eye: <Eye />,
  eyeOff: <EyeOff />,
  key: <KeyRound />,
  plus: <Plus />,
  user: <User />,
  arrowRight: <ArrowRight />,
  arrowDown: <ArrowDown />,
  arrowLeft: <ArrowLeft />,
  arrowUp: <ArrowUp />,
  check: <Check />,
  pencil: <Pencil />,
  list: <List />,
  menu: <Menu />,
  x: <X />,
  trash: <Trash2 />,
  calendar: <Calendar />,
  boxes: <Boxes />,
  search: <Search />
}